# Generated by Django 2.2.4 on 2019-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190820_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='hwid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
