# Generated by Django 2.2.4 on 2019-08-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190820_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='app',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='key',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Key'),
            preserve_default=False,
        ),
    ]
