# Generated by Django 2.2.4 on 2019-09-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190823_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='master_key',
            field=models.CharField(default='dyZNrDZxMPRD7jinky7dDUw28loqaRTe', max_length=128),
        ),
    ]
